language: haxe
cache:
    apt: true
    directories:
        - node_modules

before_install:
    - npm install
    - yes | haxelib install targets/test.hxml

install: true

before_script:
    - gulp create-artifacts-dir

script: gulp test

after_script:
    - gulp build

#whitelist only the master branch
branches:
    only:
        - master
