language: haxe
cache:
    apt: true
    directories:
        - node_modules

before_install:
    - npm install
    - yes | haxelib install targets/test.hxml

install: true

before_script:
    - gulp test
    - gulp create-bin

hxml:
    - targets/js.hxml
